version: '2.0'
services:
    web:
        build:
            context: .
        env_file: ./signalservers.env
        ports:
            - "8000:8000"
    db:
        image: postgres:9.5
        env_file: ./signalservers.env
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
volumes:
    dbdata: {}