# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-10-25 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='configuration',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.AddField(
            model_name='operation',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='policies.Policy'),
            preserve_default=False,
        ),
    ]
