# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-10-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20161024_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
