# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-11-18 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_auto_20161102_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='cut_off_number',
            field=models.FloatField(default=0),
        ),
    ]
