# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-12-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_auto_20161117_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
