# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_auto_20161209_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='file_frame_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='file_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='version',
            field=models.FloatField(default=0),
        ),
    ]
