# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-09-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_auto_20170107_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_file', models.FileField(upload_to='/var/signalserver/policies')),
                ('file_name', models.CharField(max_length=400)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
