# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-10-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=400)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=400)),
                ('group_name', models.CharField(max_length=400)),
                ('signal_name', models.CharField(max_length=400)),
                ('precentage', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
        ),
    ]
