# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-10-07 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='operation_name',
            field=models.CharField(default='average', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rule',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='signal_name',
            field=models.CharField(max_length=100),
        ),
    ]
