# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-12-10 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20161007_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('signal_name', models.CharField(max_length=100)),
                ('operation_id', models.IntegerField(default=0)),
                ('operation_name', models.CharField(max_length=20)),
                ('precentage', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
                ('cut_off', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=400)),
                ('process_id', models.IntegerField(default=0)),
                ('policy_name', models.CharField(max_length=400)),
                ('policy_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField(default=0)),
                ('group_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='rule',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.AddField(
            model_name='entry',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Summary'),
        ),
    ]
