# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-12-10 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161209_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='second_signal_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
