# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-12-10 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_entry_second_signal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='precentage',
            new_name='percentage',
        ),
    ]
