# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-09 18:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_entry_result_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('signal_name', models.CharField(max_length=100)),
                ('total_frame_number', models.IntegerField(default=0)),
                ('off_total_frame_number', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
                ('off_signal_values', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), size=None)),
                ('off_frame_times', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=400)),
                ('process_id', models.IntegerField(default=0)),
                ('policy_name', models.CharField(max_length=400)),
                ('policy_id', models.IntegerField(default=0)),
                ('file_id', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
