# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170109_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='op_id',
            field=models.IntegerField(default=0),
        ),
    ]
