# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-10-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='user_name',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
