# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-12-10 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_process_result_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='row',
            name='op_id',
            field=models.IntegerField(default=0),
        ),
    ]
