# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-15 22:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='frame_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='output',
            name='signal_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), size=None),
        ),
    ]
