# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20160815_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='frame_times',
        ),
        migrations.AddField(
            model_name='output',
            name='frame_count',
            field=models.IntegerField(default=0),
        ),
    ]
