# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-15 22:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_auto_20160815_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='frame_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='frame_times_st',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
