# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-16 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_auto_20160815_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='processed_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 22, 3, 25, 755868, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
