# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-22 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_output_processed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='frame_times_st',
        ),
    ]
