# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-22 20:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_remove_output_frame_times_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('signal_values', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), size=None)),
                ('frame_times', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='output',
            name='frame_times',
        ),
        migrations.RemoveField(
            model_name='output',
            name='signal_values',
        ),
        migrations.AddField(
            model_name='signal',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.Output'),
        ),
    ]
