# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-22 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_auto_20160822_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='output',
            name='task_id',
            field=models.CharField(default=datetime.datetime(2016, 8, 22, 21, 42, 55, 188843, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
