# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_auto_20160822_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='frame_count',
            field=models.IntegerField(default=0),
        ),
    ]
