# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-23 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_output_op_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='op_id',
        ),
    ]
