# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-09-30 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_remove_output_op_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='user_name',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
