# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_output_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=400)),
                ('processed_time', models.DateTimeField()),
                ('user_name', models.CharField(max_length=100)),
                ('policy_name', models.CharField(max_length=100)),
                ('policy_id', models.IntegerField(default=0)),
                ('shared', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('frame_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='output',
            name='processed_time',
        ),
        migrations.RemoveField(
            model_name='output',
            name='user_name',
        ),
    ]
