# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_auto_20170109_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signals.Request'),
            preserve_default=False,
        ),
    ]
