# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_auto_20170109_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='file_id',
            field=models.IntegerField(default=0),
        ),
    ]
