# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-23 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20160523_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='configuration',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 23, 0, 49, 19, 869289, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='configuration',
            field=models.ForeignKey(default=1,
                on_delete=django.db.models.deletion.CASCADE, to='operations.Configuration'),
            preserve_default=False,
        ),
    ]
