# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20160523_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='configuration_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
