# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-23 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20160523_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='variable_name',
            new_name='signal_name',
        ),
    ]
