# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-23 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20160523_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
