# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-06-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20160604_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
