# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-03-20 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_data_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_text', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(verbose_name='data uploaded')),
            ],
        ),
        migrations.AddField(
            model_name='filedata',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileuploads.Filename'),
        ),
    ]
