# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-03-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to='videos/%Y/%m/%d')),
            ],
        ),
    ]
