# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-03-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0003_auto_20160320_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='videostorage'),
        ),
    ]
