# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-01 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0004_auto_20160327_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(default='filename', max_length=400),
            preserve_default=False,
        ),
    ]
