# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-01 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0005_video_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 1, 8, 37, 4, 60146, tzinfo=utc), verbose_name='file created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 1, 8, 37, 14, 819908, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
