# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-05-02 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0006_auto_20160501_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_creation_time',
        ),
    ]
