# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-06-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0007_remove_video_file_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='/var/signalserver/files'),
        ),
    ]
