# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-06-05 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0009_result_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='cut_off_number',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='row',
            name='result_number',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
