# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-06-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0014_remove_result_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='op_name',
            field=models.CharField(max_length=200),
        ),
    ]
