# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-06-08 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0016_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
