# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-06-13 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0018_auto_20160610_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='config_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='processed_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 22, 41, 18, 894539, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
