# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-07-01 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0025_result_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='group_name',
            field=models.CharField(max_length=400),
        ),
    ]
