# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-07-01 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0026_auto_20160701_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='group_name',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
