# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0027_auto_20160701_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='frame_number',
            field=models.FloatField(default=0),
        ),
    ]
