# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-08-14 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0029_auto_20160813_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
