# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-10-25 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0031_auto_20160914_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='config_id',
            new_name='policy_id',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='config_name',
            new_name='policy_name',
        ),
    ]
