# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2016-12-10 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0033_result_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='result',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
