# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_process_file_id'),
        ('fileuploads', '0037_auto_20170106_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='outputs',
        ),
        migrations.AddField(
            model_name='video',
            name='file_processes',
            field=models.ManyToManyField(to='signals.Process'),
        ),
    ]
