# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0038_auto_20170110_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_count',
            field=models.IntegerField(default=0),
        ),
    ]
