# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160107235441 on 2017-01-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0039_auto_20170111_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_size',
            field=models.CharField(max_length=20),
        ),
    ]
